version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin